apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: foundry-instance
  namespace: kratix-platform-system
spec:
  destinationSelectors:
  - matchLabels:
      environment: dev
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: foundryinstances.foundry.platform
    spec:
      group: foundry.platform
      names:
        kind: FoundryInstance
        plural: foundryinstances
        singular: foundryinstance
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                required:
                - licenseRef
                properties:
                  licenseRef:
                    type: object
                    required: [name]
                    properties:
                      name:
                        type: string
                  foundryVersion:
                    type: string
                    pattern: ^\d+\.\d+(\.\d+)?$
                  resources:
                    type: object
                    properties:
                      cpu: {type: string}
                      memory: {type: string}
                  nfsBasePath:
                    type: string
                  storageBackend:
                    type: string
                    enum: [nfs, pvc]
                    default: nfs
                  proxySSL:
                    type: boolean
                    default: true
                  proxyPort:
                    type: integer
                    default: 443
                  adminPasswordSecretRef:
                    type: object
                    properties:
                      name: {type: string}

              status:
                type: object
                properties:
                  phase: {type: string}
                  isActive: {type: boolean}
                  connectedPlayers: {type: integer}
                  activeWorld: {type: string}
                  worldActive: {type: boolean}
                  lastSidecarUpdate: {type: string}
                  error: {type: string}
                  conditions:
                    type: array
                    items:
                      type: object
                      properties:
                        type: {type: string}
                        status: {type: string}
                        message: {type: string}
        served: true
        storage: true
  dependencies: []
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
          spec:
            rbac:
              permissions:
                - apiGroups: ["foundry.platform"]
                  resources: ["foundrylicenses"]
                  verbs: ["get", "list", "watch", "patch"]
                - apiGroups: ["external-secrets.io"]
                  resources: ["externalsecrets"]
                  verbs: ["get", "create", "update", "patch", "delete"]

            containers:
              - name: configure

                image: kratix-foundry-instance-configure:dev
                imagePullPolicy: Never
                command: ["python3", "/app/scripts/main.py"]
                env:
                  - name: NFS_SERVER_HOST
                    value: "192.168.200.184"
                  - name: NFS_BASE_PATH
                    value: "/volume1/foundry"
                volumeMounts:
                  - name: license
                    mountPath: /etc/foundry/license
                    readOnly: true
            volumes:
              - name: license
                secret:
                  secretName: foundry-license
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-delete
          spec:
            rbac:
              permissions:
                - apiGroups: ["foundry.platform"]
                  resources: ["foundrylicenses"]
                  verbs: ["get", "list", "patch"]
                - apiGroups: [""]
                  resources: ["persistentvolumeclaims"]
                  verbs: ["get", "delete"]
            containers:
              - name: cleanup
                image: kratix-foundry-instance-configure:dev
                imagePullPolicy: Never
                command: ["python3", "/app/scripts/delete.py"]
                volumeMounts:
                  - name: credentials
                    mountPath: /etc/foundry/credentials
                    readOnly: true
            volumes:
              - name: credentials
                secret:
                  secretName: foundry-credentials

    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
          spec:
            containers:
              - name: setup-dependencies
                image: ghcr.io/syntasso/kratix-pipeline-utility:v0.0.1
                command:
                  - sh
                  - -c
                  - |
                    set -ex
                    
                    # Create the foundry-vtt namespace
                    cat > /kratix/output/namespace.yaml <<EOF
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: foundry-vtt
                      labels:
                        managed-by: kratix
                        promise: foundry-instance
                    EOF
                    
                    # Create ClusterGenerator for password generation (ESO)
                    cat > /kratix/output/cluster-generator.yaml <<EOF
                    apiVersion: generators.external-secrets.io/v1alpha1
                    kind: ClusterGenerator
                    metadata:
                      name: foundry-password
                      labels:
                        managed-by: kratix
                        promise: foundry-instance
                    spec:
                      kind: Password
                      generator:
                        passwordSpec:
                          length: 24
                          digits: 4
                          symbols: 0
                          noUpper: false
                          allowRepeat: true
                    EOF
                    
                    echo "Promise dependencies configured"


