# Example: Instance with shared plugins
# This instance shares a plugin pool with main-campaign
apiVersion: foundry.platform/v1alpha1
kind: FoundryInstance
metadata:
  name: oneshot-games
  namespace: foundry-vtt
spec:
  licenseRef:
    name: primary-license
  
  # Not requesting active - will show standby page
  requestActive: false
  
  # Allow force switchover (for quick one-shot games)
  switchoverMode: force
  
  foundryVersion: "13.347.0"
  subdomain: oneshots
  
  resources:
    cpu: "100m"
    memory: "256Mi"

  # Use PVC for local testing
  storageBackend: pvc
  
  # Share plugins with main-campaign (uses same NFS path)
  plugins:
    mode: shared
    sharedWithInstance: main-campaign
  
  # New worlds folder for this instance
  worlds:
    mode: new
  
  gateway:
    parentRef:
      name: cilium-gateway-external
      namespace: default
    dnsTarget: "212.69.47.125"
