apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: foundry-password
  namespace: kratix-platform-system
spec:
  destinationSelectors:
  - matchLabels:
      environment: dev
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: foundrypasswords.foundry.platform
    spec:
      group: foundry.platform
      names:
        kind: FoundryPassword
        plural: foundrypasswords
        singular: foundrypassword
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                required:
                - type
                properties:
                  type:
                    type: string
                    description: Type of password - 'default' (shared per user) or 'instance' (unique per instance)
                    enum: [default, instance]
                  instanceRef:
                    type: object
                    description: Reference to a FoundryInstance (only for type 'instance')
                    properties:
                      name:
                        type: string
                        description: Name of the FoundryInstance this password is for
              status:
                type: object
                properties:
                  phase:
                    type: string
                    description: Current phase (Pending, Ready, Error)
                  secretName:
                    type: string
                    description: Name of the generated Kubernetes Secret
                  createdAt:
                    type: string
                    description: Timestamp when password was first generated
                  lastRefreshed:
                    type: string
                    description: Timestamp when password was last refreshed
                  error:
                    type: string
                    description: Error message if phase is Error
        served: true
        storage: true
        subresources:
          status: {}
  dependencies: []
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
          spec:
            containers:
              - name: setup-dependencies
                image: ghcr.io/syntasso/kratix-pipeline-utility:v0.0.1
                command:
                  - sh
                  - -c
                  - |
                    set -ex
                    
                    # Create ClusterGenerator for password generation (ESO)
                    cat > /kratix/output/cluster-generator.yaml <<EOF
                    apiVersion: generators.external-secrets.io/v1alpha1
                    kind: ClusterGenerator
                    metadata:
                      name: foundry-password
                      labels:
                        managed-by: kratix
                        promise: foundry-password
                    spec:
                      kind: Password
                      generator:
                        passwordSpec:
                          length: 24
                          digits: 4
                          symbols: 0
                          noUpper: false
                          allowRepeat: true
                    EOF
                    
                    echo "Promise dependencies configured"

    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: password-configure
          spec:
            rbac:
              permissions:
                - apiGroups: ["external-secrets.io"]
                  resources: ["externalsecrets"]
                  verbs: ["get", "create", "update", "patch", "delete"]

            containers:
              - name: configure
                image: kratix-foundry-password-configure:dev
                imagePullPolicy: Never
                command: ["python3", "/app/scripts/main.py"]
      delete:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: password-delete
          spec:
            rbac:
              permissions:
                - apiGroups: ["external-secrets.io"]
                  resources: ["externalsecrets"]
                  verbs: ["get", "delete"]
            containers:
              - name: cleanup
                image: kratix-foundry-password-configure:dev
                imagePullPolicy: Never
                command: ["python3", "/app/scripts/delete.py"]
