# MinIO credentials - used by MinIO server and Kratix
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: kratix-platform-system
type: Opaque
stringData:
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
---
# MinIO Object Storage - acts as the GitOps state store
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: kratix-platform-system
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z
        args: ["server", "/data", "--console-address", ":9090"]
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: accessKeyID
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-creds
              key: secretAccessKey
        ports:
        - containerPort: 9000
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: kratix-platform-system
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: api
  selector:
    app: minio
---
# Job to create the bucket (idempotent)
apiVersion: batch/v1
kind: Job
metadata:
  name: create-kratix-bucket
  namespace: kratix-platform-system
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: create-bucket
        image: minio/mc:RELEASE.2024-03-03T00-13-08Z
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Wait for MinIO to be ready
          until mc alias set local http://minio:80 minioadmin minioadmin; do
            echo "Waiting for MinIO..."
            sleep 2
          done
          mc mb --ignore-existing local/kratix
          echo "Bucket 'kratix' ready!"
      restartPolicy: OnFailure
---
# BucketStateStore - tells Kratix where to write pipeline outputs
apiVersion: platform.kratix.io/v1alpha1
kind: BucketStateStore
metadata:
  name: default
spec:
  bucketName: kratix
  endpoint: minio.kratix-platform-system.svc.cluster.local
  insecure: true
  secretRef:
    name: minio-creds
    namespace: kratix-platform-system
  authMethod: accessKey
---
# Destination - the local cluster where workloads are scheduled
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: worker-cluster
  labels:
    environment: dev
spec:
  stateStoreRef:
    kind: BucketStateStore
    name: default
  path: worker-cluster
---
# Flux credentials for MinIO
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: flux-system
type: Opaque
stringData:
  accesskey: minioadmin
  secretkey: minioadmin
---
# Flux Bucket Source - watches MinIO for state changes
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Bucket
metadata:
  name: kratix-bucket
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  bucketName: kratix
  endpoint: minio.kratix-platform-system.svc.cluster.local:80
  insecure: true
  secretRef:
    name: minio-credentials
---
# Flux Kustomization - applies manifests from the bucket to the worker-cluster path
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kratix-worker-cluster
  namespace: flux-system
spec:
  interval: 5s
  prune: true
  sourceRef:
    kind: Bucket
    name: kratix-bucket
  path: ./worker-cluster
